name: scentswapwebsite
description: "ESSENCE - Neo-Brutalism Perfume Marketplace"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  http: ^1.6.0
  uuid: ^4.5.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  supabase_flutter: ^2.9.1
  provider: ^6.1.5+1
  marquee: ^2.2.3
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/.env
